import { Milestone, TriviaQuestion, BirthdayLetter } from "@/types";

export const INITIAL_MILESTONES: Milestone[] = [
  {
    id: "m-0",
    sequence: 0,
    sceneType: "act-0-entry",
    title: "Entry Transition",
    subtitle: "A journey through our universe",
    captions: [
      "Every story begins in the silence of what was...",
      "Before a single word was spoken.",
    ],
    media: [],
    custom3DConfig: {
      splineProgressStart: 0.0,
      splineProgressEnd: 0.08,
      cameraFov: 50,
      ambientColor: "#150e28",
      fogDensity: 0.04,
      fogColor: "#0b0817",
    },
  },
  {
    id: "m-1",
    sequence: 1,
    sceneType: "act-1-before",
    title: "Before We Met",
    subtitle: "Two separate worlds",
    captions: [
      "There were two separate lives.",
      "Two stories moving forward.",
      "And somehow… they were about to cross paths.",
    ],
    media: [
      {
        id: "media-childhood-1",
        type: "image",
        url: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&q=80",
        caption: "Early childhood memories & sunlit laughter",
      },
      {
        id: "media-school-1",
        type: "image",
        url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=800&q=80",
        caption: "School days and dreaming of tomorrow",
      },
      {
        id: "media-family-1",
        type: "image",
        url: "https://images.unsplash.com/photo-1511895426328-dc8714191300?w=800&q=80",
        caption: "Cherished warmth of family",
      },
    ],
    custom3DConfig: {
      splineProgressStart: 0.08,
      splineProgressEnd: 0.18,
      cameraFov: 45,
      ambientColor: "#281232",
      fogDensity: 0.035,
      fogColor: "#170a20",
    },
  },
  {
    id: "m-2",
    sequence: 2,
    sceneType: "act-2-college",
    title: "Marine Engineering College",
    subtitle: "The Admission & Administration Hall",
    captions: [
      "A bustling marine engineering campus filled with students and parents.",
      "Documents, fee counters, and the quiet tension of admission day.",
      "Walking toward the administrative waiting area.",
    ],
    date: "Admission Day",
    location: "Marine Engineering College Administration Hall",
    media: [
      {
        id: "media-college-1",
        type: "image",
        url: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&q=80",
        caption: "The bustling college corridors where we first stood in the same room",
      },
    ],
    custom3DConfig: {
      splineProgressStart: 0.18,
      splineProgressEnd: 0.32,
      cameraFov: 42,
      ambientColor: "#1f1a2e",
      fogDensity: 0.03,
      fogColor: "#100d1a",
    },
  },
  {
    id: "m-3",
    sequence: 3,
    sceneType: "act-2-college-pen",
    title: "The Pen",
    subtitle: "The moment our lives touched",
    captions: [
      "And that was it.",
      "A pen.",
      "A smile.",
      "Two strangers.",
      "Neither of us knew how important that moment would become.",
    ],
    date: "Admission Day",
    location: "Paperwork Desk",
    media: [],
    custom3DConfig: {
      splineProgressStart: 0.32,
      splineProgressEnd: 0.38,
      cameraFov: 40,
      ambientColor: "#221c2e",
      fogDensity: 0.03,
      fogColor: "#120e1c",
    },
  },
  {
    id: "m-4",
    sequence: 4,
    sceneType: "act-2-tribly-class",
    title: "Tribaly / Classroom",
    subtitle: "Back bench to front row",
    captions: [
      "Day 1.",
      "Day 2.",
      "Still no conversation.",
      "But somehow, I kept noticing you.",
    ],
    media: [
      {
        id: "media-classroom-1",
        type: "image",
        url: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&q=80",
        caption: "Quiet glances across the lecture hall",
      },
    ],
    custom3DConfig: {
      splineProgressStart: 0.38,
      splineProgressEnd: 0.45,
      cameraFov: 42,
      ambientColor: "#201c2c",
      fogDensity: 0.03,
      fogColor: "#110e1a",
    },
  },
  {
    id: "m-5",
    sequence: 5,
    sceneType: "act-2-same-class",
    title: "The Friend Group",
    subtitle: "Six classmates & endless laughter",
    captions: [
      "Three boys in the back bench. Three girls in the front row.",
      "Studying together, helping with assignments, sharing jokes.",
      "Somehow, disturbing you became one of my favourite hobbies.",
    ],
    media: [
      {
        id: "media-friends-1",
        type: "image",
        url: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800&q=80",
        caption: "Our college circle — days filled with laughter and shared studies",
      },
    ],
    custom3DConfig: {
      splineProgressStart: 0.45,
      splineProgressEnd: 0.53,
      cameraFov: 44,
      ambientColor: "#1e1a2a",
      fogDensity: 0.028,
      fogColor: "#0f0d18",
    },
  },
  {
    id: "m-6",
    sequence: 6,
    sceneType: "act-3-train",
    title: "Kozhikode Train",
    subtitle: "Wind, sunset and open doors",
    captions: [
      "Leaving the classroom behind for the long railway journey.",
      "Safely by the doorway as golden hour bathed the landscape.",
      "Wind in our hair, the rhythm of the tracks, heading toward Kozhikode.",
    ],
    date: "The First Journey",
    location: "En route to Kozhikode",
    media: [
      {
        id: "media-train-1",
        type: "image",
        url: "https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&q=80",
        caption: "Golden hour breeze along the railway tracks",
      },
    ],
    custom3DConfig: {
      splineProgressStart: 0.53,
      splineProgressEnd: 0.61,
      cameraFov: 48,
      ambientColor: "#301d24",
      fogDensity: 0.025,
      fogColor: "#1f1017",
    },
  },
  {
    id: "m-7",
    sequence: 7,
    sceneType: "act-3-beach",
    title: "Kozhikode Beach",
    subtitle: "Sunset in the shallow waters",
    captions: [
      "The shores of Kozhikode under an amber sunset.",
      "Walking side by side, feeling the gentle waves wash over our feet.",
      "Soft sand, reflections of dusk, and conversations that felt timeless.",
    ],
    location: "Kozhikode Beach",
    media: [
      {
        id: "media-beach-1",
        type: "image",
        url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80",
        caption: "Evening tide at Kozhikode Beach",
      },
    ],
    custom3DConfig: {
      splineProgressStart: 0.61,
      splineProgressEnd: 0.68,
      cameraFov: 46,
      ambientColor: "#2a1e28",
      fogDensity: 0.025,
      fogColor: "#170f1a",
    },
  },
  {
    id: "m-8",
    sequence: 8,
    sceneType: "act-3-late-talks",
    title: "Late Night Conversations",
    subtitle: "A silent universe between us",
    captions: [
      "Somewhere between those conversations…",
      "…we stopped being just friends.",
      "…we just hadn’t said it out loud yet.",
    ],
    media: [],
    custom3DConfig: {
      splineProgressStart: 0.68,
      splineProgressEnd: 0.75,
      cameraFov: 44,
      ambientColor: "#101026",
      fogDensity: 0.035,
      fogColor: "#080816",
    },
  },
  {
    id: "m-9",
    sequence: 9,
    sceneType: "act-3-october-31",
    title: "31 AUGUST 2025",
    subtitle: "THE DAY WE BECAME US.",
    captions: [
      "31 AUGUST 2025",
      "THE DAY WE BECAME US.",
      "The unspoken truth finally found words.",
      "From that day forward, every tomorrow was ours.",
    ],
    date: "2025-08-31",
    media: [
      {
        id: "media-milestone-heart",
        type: "image",
        url: "https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=800&q=80",
        caption: "The day we officially began our journey together",
      },
    ],
    custom3DConfig: {
      splineProgressStart: 0.75,
      splineProgressEnd: 0.80,
      cameraFov: 45,
      ambientColor: "#2d0f1c",
      fogDensity: 0.032,
      fogColor: "#1a0812",
    },
  },
  {
    id: "m-10",
    sequence: 10,
    sceneType: "act-3-classic-350",
    title: "Classic 350",
    subtitle: "Royal Enfield Signals & Coastal Breeze",
    captions: [
      "Teaching Sivani to ride down by the beach road.",
      "Then riding together into the sunset, wind all around us.",
      "Holding on tight, listening to the deep steady thump of the Classic 350.",
    ],
    media: [
      {
        id: "media-classic350-1",
        type: "image",
        url: "https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=800&q=80",
        caption: "Riding into the sunset on the Classic 350",
      },
    ],
    custom3DConfig: {
      splineProgressStart: 0.80,
      splineProgressEnd: 0.86,
      cameraFov: 46,
      ambientColor: "#1c2214",
      fogDensity: 0.028,
      fogColor: "#0f150a",
    },
  },
  {
    id: "m-11",
    sequence: 11,
    sceneType: "act-3-mountain-fall",
    title: "Himalayan 450 & Mountain Fall",
    subtitle: "Climbing the heights & holding on",
    captions: [
      "Climbing into misty heights on the brown Himalayan 450.",
      "A wet patch on a steep turn — the bike slipped.",
      "We fell.",
      "We were scared.",
      "Checking frantically if you were hurt... but you were safe.",
      "Just a scraped knee, the motorcycle still standing strong.",
      "But we were okay.",
      "And that's what mattered.",
    ],
    media: [
      {
        id: "media-himalayan-1",
        type: "image",
        url: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800&q=80",
        caption: "Conquering mountain curves on the Himalayan",
      },
    ],
    custom3DConfig: {
      splineProgressStart: 0.86,
      splineProgressEnd: 0.92,
      cameraFov: 46,
      ambientColor: "#201c18",
      fogDensity: 0.035,
      fogColor: "#12100d",
    },
  },
  {
    id: "m-12",
    sequence: 12,
    sceneType: "act-3-life-together",
    title: "Home / Everyday Life",
    subtitle: "The ordinary magic of everyday love",
    captions: [
      "Visiting home, sitting together, simple teas and shared meals.",
      "Sleepy selfies, family moments, and spontaneous laughs.",
      "The quiet truth that you became my safe place.",
    ],
    media: [
      {
        id: "media-home-1",
        type: "image",
        url: "https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?w=800&q=80",
        caption: "Holding hands through every season",
      },
      {
        id: "media-food-1",
        type: "image",
        url: "https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=800&q=80",
        caption: "Shared treats and sweet cravings",
      },
    ],
    custom3DConfig: {
      splineProgressStart: 0.92,
      splineProgressEnd: 0.96,
      cameraFov: 44,
      ambientColor: "#241824",
      fogDensity: 0.028,
      fogColor: "#140d14",
    },
  },
  {
    id: "m-13",
    sequence: 13,
    sceneType: "act-4-finale",
    title: "MEMORIES OF SIVSHA",
    subtitle: "Every picture is a place we once existed together.",
    captions: [
      "A starry clearing filled with warm lanterns.",
      "A marble pedestal awaiting your touch.",
      "Tap the wax seal to open my heart to you.",
    ],
    media: [],
    custom3DConfig: {
      splineProgressStart: 0.96,
      splineProgressEnd: 1.0,
      cameraFov: 40,
      ambientColor: "#20122c",
      fogDensity: 0.02,
      fogColor: "#0e0616",
    },
  },
];

export const INITIAL_TRIVIA_QUESTIONS: TriviaQuestion[] = [
  {
    id: "q1",
    question: "What small object connected us for the very first time on admission day?",
    hint: "You gave it to my father when he needed it most.",
    acceptedAnswers: ["pen", "a pen", "the pen", "ballpoint pen", "ink pen"],
  },
  {
    id: "q2",
    question: "On which special date did we officially become 'Us'?",
    hint: "The last day of August.",
    acceptedAnswers: [
      "31 august",
      "august 31",
      "31 august 2025",
      "august 31 2025",
      "31st august",
      "31st august 2025",
      "aug 31",
      "31 aug",
      "31/08",
      "31-08",
      "31/8",
      "31-8",
      "2025-08-31",
    ],
  },
  {
    id: "q3",
    question: "Which coastal city did we travel to for our golden hour train & beach journey?",
    hint: "Famous for its beach waves and evening horizon in Kerala.",
    acceptedAnswers: [
      "kozhikode",
      "calicut",
      "kozhikkode",
      "clt",
    ],
  },
];

export const INITIAL_LETTER: BirthdayLetter = {
  id: "letter-1",
  recipientName: "Sivani",
  senderName: "Yours, Always",
  date: "Everyday & Forever",
  headline: "To Sivani — The One Who Made My World Bloom",
  paragraphs: [
    "From the moment you handed me that simple pen in the crowded college hall, you quietly rewrote the direction of my life. Who could have known that a stranger's smile on admission day would become the brightest light in every single day that followed?",
    "We have watched sunsets from open train doors, walked bare-foot through the Kozhikode tides, shared unspoken glances in crowded back seats, rode through coastal winds on the Classic 350, and climbed into the mountain clouds on the Himalayan.",
    "Even when the bike slipped on the mountain and fear gripped us, holding your hand and knowing you were safe reminded me of the only truth that has ever mattered: as long as I have you beside me, we can weather any storm.",
    "Thank you for your warmth, your laughter, your patience, and for loving me just as I am.",
    "This world, this story, and my whole heart are forever yours.",
  ],
  signature: "With all my love, forever & always",
  waxSealColor: "#be123c",
};
